### ISSUE TITLE
Fix ETH/DaggerHashimoto calculations

### ISSUE THREAD

**Issue by BitcoinLabrador** [lukechilds/howmanyconfs.com#20]
I'm not an ethereum fan, but it should be fair. Ethereum is quicker atm, so there should be a state for that. 

![image](https://user-images.githubusercontent.com/69748779/91833416-f9bcfe80-ec46-11ea-85e6-5b09b9076311.png)

**Comment by lukechilds** [comment]
That's an error, Ethereum does definitely not have more hashrate than Bitcoin at the moment.

I'm using the NiceHsh API to calculate hashrate costs. NiceHash have probably made a breaking change to their API so they have likely changed the units they're returning or something which is causing incorrect results. (this has happened before)

Unfortunately I don't have time to look into this right now, I'm very busy on something else that's higher priority, but will try to resolve the issue as soon as I'm able to.

In the meantime if anyone wants to take a look at this and submit a PR to resolve the issue I'd really appreciate it.

$50 BTC tip for anyone who submits a working PR that passes a code review.

**Comment by lukechilds** [comment]
Same issue on crypto51.app which is using the same APIs as us, reported the issue to them here: https://github.com/tdickman/crypto51/issues/59

**Comment by lukechilds** [comment]
Ok the numbers were off by a factor of 10 so I've pushed a really dirty hacky fix that does the job for now so the website isn't showing incorrect information: https://github.com/lukechilds/howmanyconfs.com/commit/a7e5f9fc8e95e9f8d5a11b0a6b0b89684d7b3abb

```diff
diff --git a/api/nicehash.js b/api/nicehash.js
index 7f94887..12390cc 100644
--- a/api/nicehash.js
+++ b/api/nicehash.js
@@ -29,6 +29,13 @@ const getNiceHashData = async () => {
 			const values = currentValues.algos.find(algo => algo.a === algorithm.id);
 			const pricePerHashPerDay = values.p / 100000000;
 			algorithm.pricePerHashPerSecond = pricePerHashPerDay / DAYS;
+			// TODO: Fix this properly.
+			// These calcs seem to be off by a factor of 10 for ETH/DaggerHashimoto.
+			// No idea why and no time to look into it right now but this dirty hack
+			// appears to be generating correct values for now.
+			if (algorithm.name === 'DaggerHashimoto') {
+				algorithm.pricePerHashPerSecond /= 10;
+			}
 			algorithm.hashrate = values.s;
 
 			algorithm.priceReadable = (pricePerHashPerDay * marketFa
```

This still needs to be fixed properly though.

**Comment by tdickman** [comment]
@lukechilds I'm getting the same numbers that I see on crypto51.app when manually calculating using the data from [here](https://www.nicehash.com/algorithm) under `DaggerHashimoto`.

Figures as of now:
* [218 TH/s](https://etherscan.io/chart/hashrate)
* [7.3954 BTC / TH / day](https://www.nicehash.com/algorithm)
* [$11900 USD / BTC](https://www.coinmarketcap.com/)

This gives us 218 * 7.3954 * 11900 / 24 = $799,381 / hr

Some rough calculations for the rewards earned (since this drives the amount of mining power thrown at each network):

The [total ethereum mining reward](https://www.etherchain.org/charts/miningReward) was 32681 ETH / day == $15.4M / 24 == $640k / hr in reward on the 31st. Note: This figure has been highly volatile over the last few days, with a minimum ~$400k / hr in reward.

The [total bitcoin mining reward](https://www.blockchain.com/charts/miners-revenue) was $12.192M / day == $508k / hr in reward on the 30th.

**Comment by tdickman** [comment]
And some stats on the sources of these fees:

# Ethereum (31st)

* block reward: [13,206 ETH](https://www.etherchain.org/charts/blockMiningReward)
* uncle reward: [580 ETH](https://www.etherchain.org/charts/uncleMiningReward)
* fee reward: [18,895 ETH](https://www.etherchain.org/charts/feeMiningReward)
* total: $1.4M

# Bitcoin (31st)

* daily block reward: [937.5 BTC](https://bitcoinvisuals.com/chain-block-reward-day)
* fee reward: [94.77 BTC](https://bitcoinvisuals.com/chain-block-reward-day)
* total: $1.2M

This means Ethereum's mining rewards exceeded Bitcoin's on the 31st, which is.. interesting.

**Comment by lukechilds** [comment]
Oh wow, that's insane!

Yeah that makes sense then. So it's just the fees that are mooning, not the hashrate.

I'm using $ price per second of total coin hashrate on NiceHash to get a very rough approximation of energy per second utilised by PoW. And then using this as an interoperable metric across chains to compare PoW strength.

But clearly this completely breaks down in crazy short term high-fee bursts such as this. Mining profitability moons, so hashrate cost on NiceHash moons, so my calculations show PoW strength mooning when in reality, the high fee environment would have to persist for a while to have a knock on effect on PoW strength.

I'll revert my patch then since the current values are "correct". guess I need to think of a more reliable method to calculate a cross comparable PoW metric.

Maybe if I can find the average energy usage and average hashrate of the popular ASICs for all the different mining algorithms and come up with a watt/hash figure for each algo. Then calculate each chains PoW strength with `algo_hashrate * algo_watt_per_hash`.

**Comment by tdickman** [comment]
Yeah, it's definitely insane. Short terms bursts like this just mean additional profitability for miners, and likely only result in additional hardware being purchased in these are sustained for several months.

**Comment by lukechilds** [comment]
Ok, I've reverted my patch: https://github.com/lukechilds/howmanyconfs.com/commit/2e219d0f1946517584c923d04a2646eab7ab86a2

Thanks for your input @tdickman!

Closing this issues since the calculations are working correctly. I just need to have a think about how I can take a different approach in the approximations so they don't get so distorted by high-fee bursts.

And thanks for reporting @BitcoinLabrador.
