### ISSUE TITLE
Where is the difficulty ?

### ISSUE THREAD

**Issue by dArkjON** [lukechilds/howmanyconfs.com#6]
Hey,
its look like a interesting project also the stastistic is in a good overview but one main parameter to compare different Algos also different Hashrates is the difficulty.

> For example if Bitcoin has a hashrate of SHA-256 @ 40 PH/s and Bitcoin Cash has a hashrate of SHA-256 @ 2 PH/s, it's easy to see that for a given period of time the Bitcoin blockchain will have 20x (40/2) the amount of work securing it than the Bitcoin Cash blockchain

The amount of "more secure" work in this time is just to guess the right nounce to match the prefix 0 from the difficulty in this Proof of Work Chain. Its not more secure or lesser secure its just a random Number with enough 0 infront to verfiy the right block.

Your overview :

Bitcoin (BTC) | $142.35 B | SHA-256 @ 52,262 PH/s | 6 confs | 55m 6s | -
-- | -- | -- | -- | -- | --
Bitcoin Cash (BCH) | $7.37 B | SHA-256 @ 2,418 PH/s | 125 confs | 19h 53m | 22x slower
Bitcoin SV (BSV) | $1.15 B | SHA-256 @ 426 PH/s | 631 confs | 4d 16h | 123x slower
Litecoin Cash (LCC) | $6.49 M | SHA-256 @ 8 PH/s | 201.059 confs | 242d 22m | 6.325x slower

And here the Difficulty Overview for SHA 256

Bitcoin Difficulty | 6,704,632,680,587 | (1x)
-- | -- | --
Bitcoin Cash Difficulty | 325,914,761,076 | (20,5x)
Bitcoin SV Difficulty |  66,795,632,530 | (100)
LitecoinCash | 219,703,639 | (30516x)

If we compare the difficulty overview to your overview for example BTC vs. BCH there is 21,61x more mining Power in Bitcoin but als the Difficulty is 20,5x higher than BCH. Is we multiplied the Hashrate 2418 x 20,5 its like 49,569 the different here is ~5% and not x22

Bitcoin SV have 426PH x 100 Difficulty Diff = 42,600 = ~19% and not x 123
Litecoin Cash have 8PH x 30516 Difficulty Diff = 244,128 = Bitcoin Mining Value x 4,6

Its looks like Litecoin Cash have a 4,6x faster mining power based on difficulty as bitcoin and its not 6325x slower because its dont need the same luck as bitcoin with there nounce but its not more or less secure in this moment.

At least comparing other Algos with SHA 256 is also not possible with just calculate the price for a rented hashrate there many more factors, SHA 256 is the easiest Algo to mine and without a difficulty calcuation,, a revenue overview or a GPU or ASIC comparison the column "Difference" dont state any real value more a random multiplier.

Bitcoin Antminer S17 | 53 TH/s | $2030
--|--|--
Litecoin Antminer L3++ | 580 MH/s | $213

If we do some simple math here - 53000000 MH/s / 580 MH/S = 91379
your statement looks like "1 x S17 is comparable to 91379 x L3+ and this is nonsense.

Maybe you should add colums like difficulty and also a "algo waste multi" to get real and fair values.

**Comment by lukechilds** [comment]
>If we compare the difficulty overview to your overview for example BTC vs. BCH there is 21,61x more mining Power in Bitcoin but als the Difficulty is 20,5x higher than BCH. Is we multiplied the Hashrate 2418 x 20,5 its like 49,569 the different here is ~5% and not x22

The difficulty is 20x higher *because* it has 20x more hashrate. It's already indirectly taken into account by using the NiceHash costs.

>If we do some simple math here - 53000000 MH/s / 580 MH/S = 91379
your statement looks like "1 x S17 is comparable to 91379 x L3+ and this is nonsense.

I'm really not sure what you mean by this. You're comparing hashes per second across different hashing algorithms so the values are not directly comparable. The calculations I'm using don't do that.

Did you read through the whole readme? I explain in detail the calculations I'm doing and what they mean.

**Comment by dArkjON** [comment]
> The difficulty is 20x higher _because_ it has 20x more hashrate. It's already indirectly taken into account by using the NiceHash costs.

There is no difficulty in the Nicehash costs included... if we compare BTC, BCH, BSV and LCC this 
coins are all SHA-256 and cost all the same amount **_1 PH / Day - 0,043 BTC_**

![Image](https://i.imgur.com/rsnnnEl.png)

**_1 PH / Script     = 600 BTC each Day
1 PH / SHA256 = 0.043 BTC each Day_**

Its still nonsense to compare the price rates talk about this coin is "slower" or "faster" its just cheaper or expensiver to rent the power.

Also Proof of Work dont do "more work" for more Power, its just a randon game where the nounce
it getting higher and higher till the Blockhash is valid. Its also not a indicator for Blockchain speed.

![Image](https://lhartikk.github.io/assets/difficulty_examples.png)

The main indicators for blockchain speed like Difficulty, Blocktime, als Blocksize are not considered in your overview and its still a joke to compare the "rent cost" and give a statement about the chain speed.

**Comment by lukechilds** [comment]
>Also Proof of Work dont do "more work" for more Power

Yes it does, that's literally what it means. "work" = "how much energy is consumed".

>Its also not a indicator for Blockchain speed.

It depends what you mean by speed here. In this instance we are talking about how much time it takes to have the same amount of "work done" to secure a blockchain.

If Bitcoin has 20x the amount of energy/hashrate/work on it than BCH, then it will take 20x longer before a BCH transaction is backed by the same thermodynamic guarantee of immutability as a BTC transaction. Therefore, in the context of thermodynamic backed immutability, BCH is 20x slower.

>The main indicators for blockchain speed like Difficulty, Blocktime, als Blocksize are not considered in your overview and its still a joke to compare the "rent cost" and give a statement about the chain speed.

All we care about is how hashrate translates to energy cost so we can compare hashrate across different algorithms. Block time/difficulty are indeed taken into account because we use the hashrate of the entire chain and divide that by the current average block time. Difficulty is dynamically adjusted as a product of hashrate and blocktime.

When we talk about speed in this context, it's not a race to see who can get the most confirmations first or a single confirmation first. It's a race to see who can accumulate an amount of work equivalent to 6 BTC confirmations first.

**Comment by lukechilds** [comment]
Please fully read the readme before continuing the discussion. Everything is explained there.

Feel free to ask any questions if anything is unclear.
