### ISSUE TITLE
A dash transaction is now as secure as a 6 conf bitcoin transaction in about 2 seconds

### ISSUE THREAD

**Issue by bitedgecom** [lukechilds/howmanyconfs.com#9]
With chain looked instant send now activated a dash transaction is secure about 1800 x faster than bitcoin. Details here,

https://blog.dash.org/mitigating-51-attacks-with-llmq-based-chainlocks-7266aa648ec9

**Comment by lukechilds** [comment]
Thanks but not really relevant to this project.

>Compare the time required for an equivalent amount of work to be completed between different Proof-of-Work blockchains.

https://github.com/lukechilds/howmanyconfs.com#howmanyconfscom

>This puts quite some trust into CLSIG messages and the Masternode network, but we consider this to be an acceptable tradeoff.

https://blog.dash.org/mitigating-51-attacks-with-llmq-based-chainlocks-7266aa648ec9

**Comment by dazbarlby** [comment]
Your site asks "How many confirmations are equivalent* to 6 Bitcoin confirmations?", meaning how many confirmation in other networks produce the equivalent security to 6 Bitcoin confirmations. In Dash's case that equivalent is 0 confirmations because LLMQ Instantsend signs and locks the transactions until it is confirmed. If you want to be very strict you could say 1 chainlocked confirmation because once a block is chainlocked no amount of computing power will be able to reorganize the blockchain.

> This puts quite some trust into CLSIG messages and the Masternode network
So you mean users need to trust the network and math, just like the bitcoin network. The Masternodes are chosen randomly to form quorums that signed the messages and they are incentivized to work for the network, not against it. Users are told when an LLMQ transaction has been signed and if there is ever a time when a transaction could not be signed, users can wait for the first chainlocked block (blocks are created every 2.5 minutes). Only at this point i.e. LLMQ InstandSend fails and Blocks are unable to be chain locked does the figure on your site apply, but that would be very very rare and users would be notified by the Dash Core wallet.

**Comment by lukechilds** [comment]
>Your site asks "How many confirmations are equivalent* to 6 Bitcoin confirmations?", meaning how many confirmation in other networks produce the equivalent security to 6 Bitcoin confirmations.

That's not what that means, in fact if you read the readme which the asterisk links to you'll see I explicitly state that's not what it means.

**Comment by dazbarlby** [comment]
Wow, making the * a link that does not look like a link and not including the information relating to the * is really devious. Why not put the information at the foot of the page?

The comparative strength/security of blockchains is exactly what you're comparing as stated in the first paragraph of the text file you referred to.

>  For example if Bitcoin has a hashrate of SHA-256 @ 40 PH/s and Bitcoin Cash has a hashrate of SHA-256 @ 2 PH/s, it's easy to see that for a given period of time the Bitcoin blockchain will have 20x (40/2) the amount of work **securing** it than the Bitcoin Cash blockchain. 

The fact that the text goes on to explain that you are using NiceHash and $/s cost to come to this strength comparison due to the differing hashing algorithms does not change the goal of the site.

What your site does not take into account are other methods of securing a blockchain. Dash secures its blockchain to a higher standard than Bitcoin, at a lower financial and environment cost.

**Comment by lukechilds** [comment]
>Wow, making the * a link that does not look like a link and not including the information relating to the * on the same page is really devious.

An asterisk that is a link is pretty standard practise. It also changes the cursor to a pointer and changes colour when you hover over it. I'm not sure how I could possibly make it more clear.

>The comparative strength/security of blockchains is exactly what you're comparing as stated in the first paragraph of the text file you referred to.

No it isn't, you highlighted the wrong part in your quote:

>the **amount of work** securing it than the Bitcoin Cash blockchain

Some more excerpts from the readme where I've clarified this:

>### These metrics are measuring "work done", not security.
>
>More "work done" doesn't necessarily mean "more security".

>### Accurately calculating security is much more complicated.
>
>These metrics give a good estimated value to compare the hashrate accross different Proof-of-Work blockchains.
>
>However to calculate if a payment can be considered "finalised" involves many more variables.
 ---

>What your site does not take into account are other methods of securing a blockchain.

Yes, that's correct, this site is to compare the time required for an equivalent amount of work to be completed between different Proof-of-Work blockchains. That's it. Nothing else. I've gone out of my way to explain at great length in the readme that "security" is a general term that is much more complicated than this one metric.
